<?php
// xhtml5.php
// combinateurs phpfxc pour le dialecte xml xhtml5
//
// code php généré par phpfxc, dévellopé spécialement pour le projet.
// voir fxc/fxc.php et fxc/generate.php
//
//

namespace fxc;      
require_once 'fxc.php';

// Elements
function A() { return Element('a', func_get_args()); }
function Abbr() { return Element('abbr', func_get_args()); }
function Address() { return Element('address', func_get_args()); }
function Article() { return Element('article', func_get_args()); }
function Aside() { return Element('aside', func_get_args()); }
function Audio() { return Element('audio', func_get_args()); }
function B() { return Element('b', func_get_args()); }
function Bdo() { return Element('bdo', func_get_args()); }
function Blockquote() { return Element('blockquote', func_get_args()); }
function Body() { return Element('body', func_get_args()); }
function Button() { return Element('button', func_get_args()); }
function Canvas() { return Element('canvas', func_get_args()); }
function Caption() { return Element('caption', func_get_args()); }
function Cite() { return Element('cite', func_get_args()); }
function Code() { return Element('code', func_get_args()); }
function Colgroup() { return Element('colgroup', func_get_args()); }
function Command() { return Element('command', func_get_args()); }
function Datalist() { return Element('datalist', func_get_args()); }
function Dd() { return Element('dd', func_get_args()); }
function Del() { return Element('del', func_get_args()); }
function Details() { return Element('details', func_get_args()); }
function Dfn() { return Element('dfn', func_get_args()); }
function Div() { return Element('div', func_get_args()); }
function Dl() { return Element('dl', func_get_args()); }
function Dt() { return Element('dt', func_get_args()); }
function Em() { return Element('em', func_get_args()); }
function Fieldset() { return Element('fieldset', func_get_args()); }
function Figcaption() { return Element('figcaption', func_get_args()); }
function Figure() { return Element('figure', func_get_args()); }
function Footer() { return Element('footer', func_get_args()); }
function Form() { return Element('form', func_get_args()); }
function H1() { return Element('h1', func_get_args()); }
function H2() { return Element('h2', func_get_args()); }
function H3() { return Element('h3', func_get_args()); }
function H4() { return Element('h4', func_get_args()); }
function H5() { return Element('h5', func_get_args()); }
function H6() { return Element('h6', func_get_args()); }
function Head() { return Element('head', func_get_args()); }
function Header() { return Element('header', func_get_args()); }
function Hgroup() { return Element('hgroup', func_get_args()); }
function Html() { return Element('html', func_get_args()); }
function I() { return Element('i', func_get_args()); }
function Iframe() { return Element('iframe', func_get_args()); }
function Ins() { return Element('ins', func_get_args()); }
function Kbd() { return Element('kbd', func_get_args()); }
function Label() { return Element('label', func_get_args()); }
function Legend() { return Element('legend', func_get_args()); }
function Li() { return Element('li', func_get_args()); }
function Map() { return Element('map', func_get_args()); }
function Mark() { return Element('mark', func_get_args()); }
function Menu() { return Element('menu', func_get_args()); }
function Meter() { return Element('meter', func_get_args()); }
function Nav() { return Element('nav', func_get_args()); }
function Noscript() { return Element('noscript', func_get_args()); }
function Object() { return Element('object', func_get_args()); }
function Ol() { return Element('ol', func_get_args()); }
function Optgroup() { return Element('optgroup', func_get_args()); }
function Option() { return Element('option', func_get_args()); }
function Output() { return Element('output', func_get_args()); }
function P() { return Element('p', func_get_args()); }
function Pre() { return Element('pre', func_get_args()); }
function Progress() { return Element('progress', func_get_args()); }
function Q() { return Element('q', func_get_args()); }
function Rp() { return Element('rp', func_get_args()); }
function Rt() { return Element('rt', func_get_args()); }
function Ruby() { return Element('ruby', func_get_args()); }
function Samp() { return Element('samp', func_get_args()); }
function Script() { return Element('script', func_get_args()); }
function Section() { return Element('section', func_get_args()); }
function Select() { return Element('select', func_get_args()); }
function Small() { return Element('small', func_get_args()); }
function Span() { return Element('span', func_get_args()); }
function Strong() { return Element('strong', func_get_args()); }
function Style() { return Element('style', func_get_args()); }
function Sub() { return Element('sub', func_get_args()); }
function Summary() { return Element('summary', func_get_args()); }
function Sup() { return Element('sup', func_get_args()); }
function Table() { return Element('table', func_get_args()); }
function Tbody() { return Element('tbody', func_get_args()); }
function Td() { return Element('td', func_get_args()); }
function Textarea() { return Element('textarea', func_get_args()); }
function Tfoot() { return Element('tfoot', func_get_args()); }
function Th() { return Element('th', func_get_args()); }
function Thead() { return Element('thead', func_get_args()); }
function Time() { return Element('time', func_get_args()); }
function Title() { return Element('title', func_get_args()); }
function Tr() { return Element('tr', func_get_args()); }
function Ul() { return Element('ul', func_get_args()); }
function Var_() { return Element('var', func_get_args()); }
function Video() { return Element('video', func_get_args()); }


// Empty Elements
function Area() { return EmptyElement('area', func_get_args()); }
function Base() { return EmptyElement('base', func_get_args()); }
function Br() { return EmptyElement('br', func_get_args()); }
function Col() { return EmptyElement('col', func_get_args()); }
function Embed() { return EmptyElement('embed', func_get_args()); }
function Hr() { return EmptyElement('hr', func_get_args()); }
function Img() { return EmptyElement('img', func_get_args()); }
function Input() { return EmptyElement('input', func_get_args()); }
function Keygen() { return EmptyElement('keygen', func_get_args()); }
function Link() { return EmptyElement('link', func_get_args()); }
function Menuitem() { return EmptyElement('menuitem', func_get_args()); }
function Meta() { return EmptyElement('meta', func_get_args()); }
function Param() { return EmptyElement('param', func_get_args()); }
function Source() { return EmptyElement('source', func_get_args()); }
function Track() { return EmptyElement('track', func_get_args()); }
function Wbr() { return EmptyElement('wbr', func_get_args()); }


// Attributes
function accept($v) { return attr('accept', $v); }
function acceptCharset($v) { return attr('accept-charset', $v); }
function accesskey($v) { return attr('accesskey', $v); }
function action($v) { return attr('action', $v); }
function alt($v) { return attr('alt', $v); }
function async($v) { return attr('async', $v); }
function autocomplete($v) { return attr('autocomplete', $v); }
function autofocus($v) { return attr('autofocus', $v); }
function autoplay($v) { return attr('autoplay', $v); }
function challenge($v) { return attr('challenge', $v); }
function charset($v) { return attr('charset', $v); }
function checked($v) { return attr('checked', $v); }
function cite_($v) { return attr('cite', $v); }
function class_($v) { return attr('class', $v); }
function cols($v) { return attr('cols', $v); }
function colspan($v) { return attr('colspan', $v); }
function content($v) { return attr('content', $v); }
function contenteditable($v) { return attr('contenteditable', $v); }
function contextmenu($v) { return attr('contextmenu', $v); }
function controls($v) { return attr('controls', $v); }
function coords($v) { return attr('coords', $v); }
function data($v) { return attr('data', $v); }
function datetime($v) { return attr('datetime', $v); }
function defer($v) { return attr('defer', $v); }
function dir($v) { return attr('dir', $v); }
function disabled($v) { return attr('disabled', $v); }
function draggable($v) { return attr('draggable', $v); }
function enctype($v) { return attr('enctype', $v); }
function for_($v) { return attr('for', $v); }
function form_($v) { return attr('form', $v); }
function formaction($v) { return attr('formaction', $v); }
function formenctype($v) { return attr('formenctype', $v); }
function formmethod($v) { return attr('formmethod', $v); }
function formnovalidate($v) { return attr('formnovalidate', $v); }
function formtarget($v) { return attr('formtarget', $v); }
function headers($v) { return attr('headers', $v); }
function height($v) { return attr('height', $v); }
function hidden($v) { return attr('hidden', $v); }
function high($v) { return attr('high', $v); }
function href($v) { return attr('href', $v); }
function hreflang($v) { return attr('hreflang', $v); }
function httpEquiv($v) { return attr('http-equiv', $v); }
function icon($v) { return attr('icon', $v); }
function id($v) { return attr('id', $v); }
function ismap($v) { return attr('ismap', $v); }
function item($v) { return attr('item', $v); }
function itemprop($v) { return attr('itemprop', $v); }
function keytype($v) { return attr('keytype', $v); }
function label_($v) { return attr('label', $v); }
function lang($v) { return attr('lang', $v); }
function list_($v) { return attr('list', $v); }
function loop($v) { return attr('loop', $v); }
function low($v) { return attr('low', $v); }
function manifest($v) { return attr('manifest', $v); }
function max($v) { return attr('max', $v); }
function maxlength($v) { return attr('maxlength', $v); }
function media($v) { return attr('media', $v); }
function method($v) { return attr('method', $v); }
function min($v) { return attr('min', $v); }
function multiple($v) { return attr('multiple', $v); }
function name($v) { return attr('name', $v); }
function novalidate($v) { return attr('novalidate', $v); }
function onbeforeonload($v) { return attr('onbeforeonload', $v); }
function onbeforeprint($v) { return attr('onbeforeprint', $v); }
function onblur($v) { return attr('onblur', $v); }
function oncanplay($v) { return attr('oncanplay', $v); }
function oncanplaythrough($v) { return attr('oncanplaythrough', $v); }
function onchange($v) { return attr('onchange', $v); }
function oncontextmenu($v) { return attr('oncontextmenu', $v); }
function onclick($v) { return attr('onclick', $v); }
function ondblclick($v) { return attr('ondblclick', $v); }
function ondrag($v) { return attr('ondrag', $v); }
function ondragend($v) { return attr('ondragend', $v); }
function ondragenter($v) { return attr('ondragenter', $v); }
function ondragleave($v) { return attr('ondragleave', $v); }
function ondragover($v) { return attr('ondragover', $v); }
function ondragstart($v) { return attr('ondragstart', $v); }
function ondrop($v) { return attr('ondrop', $v); }
function ondurationchange($v) { return attr('ondurationchange', $v); }
function onemptied($v) { return attr('onemptied', $v); }
function onended($v) { return attr('onended', $v); }
function onerror($v) { return attr('onerror', $v); }
function onfocus($v) { return attr('onfocus', $v); }
function onformchange($v) { return attr('onformchange', $v); }
function onforminput($v) { return attr('onforminput', $v); }
function onhaschange($v) { return attr('onhaschange', $v); }
function oninput($v) { return attr('oninput', $v); }
function oninvalid($v) { return attr('oninvalid', $v); }
function onkeydown($v) { return attr('onkeydown', $v); }
function onkeyup($v) { return attr('onkeyup', $v); }
function onload($v) { return attr('onload', $v); }
function onloadeddata($v) { return attr('onloadeddata', $v); }
function onloadedmetadata($v) { return attr('onloadedmetadata', $v); }
function onloadstart($v) { return attr('onloadstart', $v); }
function onmessage($v) { return attr('onmessage', $v); }
function onmousedown($v) { return attr('onmousedown', $v); }
function onmousemove($v) { return attr('onmousemove', $v); }
function onmouseout($v) { return attr('onmouseout', $v); }
function onmouseover($v) { return attr('onmouseover', $v); }
function onmouseup($v) { return attr('onmouseup', $v); }
function onmousewheel($v) { return attr('onmousewheel', $v); }
function ononline($v) { return attr('ononline', $v); }
function onpagehide($v) { return attr('onpagehide', $v); }
function onpageshow($v) { return attr('onpageshow', $v); }
function onpause($v) { return attr('onpause', $v); }
function onplay($v) { return attr('onplay', $v); }
function onplaying($v) { return attr('onplaying', $v); }
function onprogress($v) { return attr('onprogress', $v); }
function onpropstate($v) { return attr('onpropstate', $v); }
function onratechange($v) { return attr('onratechange', $v); }
function onreadystatechange($v) { return attr('onreadystatechange', $v); }
function onredo($v) { return attr('onredo', $v); }
function onresize($v) { return attr('onresize', $v); }
function onscroll($v) { return attr('onscroll', $v); }
function onseeked($v) { return attr('onseeked', $v); }
function onseeking($v) { return attr('onseeking', $v); }
function onselect($v) { return attr('onselect', $v); }
function onstalled($v) { return attr('onstalled', $v); }
function onstorage($v) { return attr('onstorage', $v); }
function onsubmit($v) { return attr('onsubmit', $v); }
function onsuspend($v) { return attr('onsuspend', $v); }
function ontimeupdate($v) { return attr('ontimeupdate', $v); }
function onundo($v) { return attr('onundo', $v); }
function onunload($v) { return attr('onunload', $v); }
function onvolumechange($v) { return attr('onvolumechange', $v); }
function onwaiting($v) { return attr('onwaiting', $v); }
function open($v) { return attr('open', $v); }
function optimum($v) { return attr('optimum', $v); }
function pattern($v) { return attr('pattern', $v); }
function ping($v) { return attr('ping', $v); }
function placeholder($v) { return attr('placeholder', $v); }
function preload($v) { return attr('preload', $v); }
function pubdate($v) { return attr('pubdate', $v); }
function radiogroup($v) { return attr('radiogroup', $v); }
function readonly($v) { return attr('readonly', $v); }
function rel($v) { return attr('rel', $v); }
function required($v) { return attr('required', $v); }
function reversed($v) { return attr('reversed', $v); }
function rows($v) { return attr('rows', $v); }
function rowspan($v) { return attr('rowspan', $v); }
function sandbox($v) { return attr('sandbox', $v); }
function scope($v) { return attr('scope', $v); }
function scoped($v) { return attr('scoped', $v); }
function seamless($v) { return attr('seamless', $v); }
function selected($v) { return attr('selected', $v); }
function shape($v) { return attr('shape', $v); }
function size($v) { return attr('size', $v); }
function sizes($v) { return attr('sizes', $v); }
function span_($v) { return attr('span', $v); }
function spellcheck($v) { return attr('spellcheck', $v); }
function src($v) { return attr('src', $v); }
function srcdoc($v) { return attr('srcdoc', $v); }
function start($v) { return attr('start', $v); }
function step($v) { return attr('step', $v); }
function style_($v) { return attr('style', $v); }
function subject($v) { return attr('subject', $v); }
function summary_($v) { return attr('summary', $v); }
function tabindex($v) { return attr('tabindex', $v); }
function target($v) { return attr('target', $v); }
function title_($v) { return attr('title', $v); }
function type($v) { return attr('type', $v); }
function usemap($v) { return attr('usemap', $v); }
function value($v) { return attr('value', $v); }
function width($v) { return attr('width', $v); }
function wrap($v) { return attr('wrap', $v); }
function xmlns($v) { return attr('xmlns', $v); }
